# Generated by Django 2.0.7 on 2020-11-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressid', models.IntegerField(db_column='addressId', primary_key=True, serialize=False)),
                ('addressname', models.CharField(blank=True, db_column='addressName', max_length=55, null=True)),
            ],
            options={
                'db_table': 'Address',
                'managed': False,
            },
        ),
    ]
